services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    restart: always
    container_name: node
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres-volume: